
sudo apt-get install vim-gnome python-dev python3-dev
sudo apt-get install cmake git 


# mount a parition at start
append the following line to /etc/fstab, then reboot
UUID=2d6b6ffe-ff65-4d93-8110-29c9f80be730 /home/oldhome   ext4    defaults        0       0

# 安装Vundle:
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# 安装youcompleteme
	安装Vundle，然后在vim中运行PluginList检查是否添加了youcompleteme
	如果添加了，那么:PluginInstall(下载和安装ycm)
	终端上运行 install.py --clang-completer

